rollout_fn:
  _target_: src.runners.humanoid_bench_runner.make_rollout_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  env_id: ${env.name}

eval_fn:
  _target_: src.runners.humanoid_bench_runner.make_eval_fn
  _partial_: true
  max_episode_steps: ${algorithm.max_episode_steps}
  env_id: ${env.name}
  
train_fn:
  _target_: src.algorithms.training.make_loop_train_fn
  _partial_: true
  max_episode_steps: ${algorithm.max_episode_steps}
  stochastic_eval: True
  filter_success: ${env.demo.filter_success}
  cut_at_first_success: ${env.demo.cut_at_first_success}
  critic_offline_warmup_iters: ${algorithm.critic_offline_warmup_iters}