rollout_fn:
  _target_: src.runners.humanoid_bench_runner.make_rollout_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  num_envs: ${algorithm.num_envs}
  env_id: ${env.name}
  data_type: ${algorithm.data_type}
  filter_success: ${env.filter_success}
  cut_at_first_success: ${env.cut_at_first_success}

eval_fn:
  _target_: src.runners.humanoid_bench_runner.make_eval_fn
  _partial_: true
  max_episode_steps: ${algorithm.max_episode_steps}
  env_id: ${env.name}
  data_type: ${algorithm.data_type}
  filter_success: ${env.filter_success}
  cut_at_first_success: ${env.cut_at_first_success}

train_fn:
  _target_: src.algorithms.training.make_loop_train_fn
  _partial_: true
  total_time_steps: ${algorithm.total_time_steps}
  num_steps: ${algorithm.num_steps}
  num_envs: ${algorithm.num_envs}
  num_eval: ${algorithm.num_eval}
  max_episode_steps: ${algorithm.max_episode_steps}
  stochastic_eval: ${env.stochastic_eval}
  cut_at_first_success: ${env.cut_at_first_success}
  critic_offline_warmup_iters: ${algorithm.critic_offline_warmup_iters}