rollout_fn:
  _target_: src.runners.maniskill_runner.make_rollout_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  num_envs: ${algorithm.num_envs}
  demo_path: ${env.demo.demo_path}
  bc_indicator: ${algorithm.bc_indicator}
  env_id: ${env.name}
  filter_success: ${env.demo.filter_success}
  cut_at_first_success: ${env.demo.cut_at_first_success}

eval_fn:
  _target_: src.runners.maniskill_runner.make_eval_fn
  _partial_: true
  max_episode_steps: ${algorithm.max_episode_steps}
  demo_path: ${env.demo.demo_path}
  bc_indicator: ${algorithm.bc_indicator}
  env_id: ${env.name}
  filter_success: ${env.demo.filter_success}
  cut_at_first_success: ${env.demo.cut_at_first_success}
  
train_fn:
  _target_: src.algorithms.training.make_loop_train_fn
  _partial_: true
  num_steps: ${algorithm.num_steps}
  total_time_steps: ${algorithm.total_time_steps}
  num_envs: ${algorithm.num_envs}
  num_eval: ${algorithm.num_eval}
  max_episode_steps: ${algorithm.max_episode_steps}
  stochastic_eval: True
  decay_rate: ${algorithm.online_sample_decay_rate}
  filter_success: ${env.demo.filter_success}
  cut_at_first_success: ${env.demo.cut_at_first_success}
  critic_offline_warmup_iters: ${algorithm.critic_offline_warmup_iters}
  critic_mixed_warmup_iters: ${algorithm.critic_mixed_warmup_iters}
  mixed_offline_start_ratio: ${algorithm.mixed_offline_start_ratio}
